#pragma once
/// @file cerberus_smdi.hpp
/// @copyright Copyright (c) 2026 D Hargreaves. All rights reserved.
///
/// SMDU — Super Maintenance Database User
/// =======================================
///
/// The SMDU is the SINGLE master administrator identity shared between
/// PsiForceDB and the local Cerberus instance. It is NOT generated by
/// Cerberus — it is provisioned FROM PsiForceDB's master administrator
/// during installation. The end user sets it once; thereafter the device
/// owns it and no cloud service ever sees the key material.
///
/// Trust model:
///   1. PsiForceDB master administrator creates the SMDU identity.
///   2. During Cerberus installation, the user provides the SMDU
///      passphrase. This passphrase is NEVER stored anywhere.
///   3. The passphrase + per-install salt are fed to LFSSL Argon2id
///      to derive the master secret.
///   4. The master secret unwraps a Kyber-1024 keypair that was
///      provisioned from PsiForceDB. The public key is written to
///      the Local Maintenance DB header. The private key is wrapped
///      (encrypted) and stored on disk; it is only unwrapped into
///      RAM on unlock.
///   5. All Local Maintenance DB pages are AES-256-GCM encrypted under
///      a sub-key derived from the Kyber shared secret.
///   6. The private key is scrubbed from RAM on lock / shutdown.
///
/// End-to-end encryption:
///   - Local DB: encrypted at rest with AES-256-GCM.
///   - Intra-device: encrypted in transit between processes using
///     the same SMDU-derived key material.
///   - Device-to-PsiForceDB: Kyber-encapsulated shared secret
///     established per session; no plaintext keys on wire.
///
/// BOUNDARY: Argon2id, Kyber keygen/encaps/decaps, AES-256-GCM
/// are delegated to LFSSL. Cerberus never implements a primitive.
/// It only stores encrypted key material and orchestrates unlock.
///
/// © 2026 D Hargreaves | LamiaFabrica Software

#include <string>
#include <vector>
#include <cstdint>
#include <memory>
#include <optional>

namespace hq::cerberus::privacy {

// ---------------------------------------------------------------------------
// WrappedKey — encrypted key material stored on disk
// ---------------------------------------------------------------------------
struct WrappedKey {
    std::vector<std::uint8_t> ciphertext;    // encrypted private key
    std::vector<std::uint8_t> nonce;         // AES-GCM nonce
    std::vector<std::uint8_t> tag;           // AES-GCM auth tag
    std::vector<std::uint8_t> wrapping_salt; // salt for wrapping key derivation
};

// ---------------------------------------------------------------------------
// KyberKeypair — public key always visible; private key only in session
// ---------------------------------------------------------------------------
struct KyberKeypair {
    std::vector<std::uint8_t> public_key;   // 1 568 bytes (Kyber-1024)
    // private_key is NEVER stored here in plaintext.
    // It lives encrypted on disk (WrappedKey) and is unwrapped into
    // session memory on SMDU::unlock(), then scrubbed on lock.
};

// ---------------------------------------------------------------------------
// SMDU — Super Maintenance Database User (single master administrator)
// ---------------------------------------------------------------------------
class SMDU {
public:
    /// Provision a new SMDU from PsiForceDB master administrator parameters.
    /// Called ONCE during installation. The passphrase is NOT stored.
    /// @param passphrase       User-provided SMDU passphrase.
    /// @param master_salt      Per-install salt generated by PsiForceDB.
    /// @param provisioned_pub  Kyber public key provided by PsiForceDB master.
    /// @return                 The provisioned SMDU, or nullopt if LFSSL absent.
    static std::optional<SMDU> provision(
        std::string_view passphrase,
        const std::vector<std::uint8_t>& master_salt,
        const std::vector<std::uint8_t>& provisioned_pub);

    /// Unlock an existing SMDU from passphrase + stored wrapped key.
    /// Re-derives the wrapping key via Argon2id, unwraps the private key
    /// into session memory, and marks the session active.
    static std::optional<SMDU> unlock(
        std::string_view passphrase,
        const std::vector<std::uint8_t>& master_salt,
        const WrappedKey& wrapped);

    /// Lock the session — scrub all sensitive material from RAM.
    void lock();

    /// Query whether the session is currently unlocked.
    [[nodiscard]] bool is_unlocked() const noexcept { return session_active_; }

    /// The per-install salt (non-secret, unique per device).
    [[nodiscard]] const std::vector<std::uint8_t>& salt() const noexcept { return salt_; }

    /// Kyber public key (provisioned from PsiForceDB master).
    [[nodiscard]] const KyberKeypair& kyber_keypair() const noexcept { return kyber_; }

    /// Derive the AES-256-GCM database encryption key.
    /// Only valid while unlocked.
    [[nodiscard]] std::optional<std::vector<std::uint8_t>> derive_db_key() const;

    /// Derive a session key for device-to-PsiForceDB E2E encryption.
    /// Uses Kyber encapsulation against the master public key.
    [[nodiscard]] std::optional<std::vector<std::uint8_t>> derive_e2e_key() const;

    /// Export the wrapped private key for persistent storage.
    [[nodiscard]] std::optional<WrappedKey> export_wrapped_key() const;

    // MANDATORY unavailable_reason per AGENTS.md
    [[nodiscard]] static std::string unavailable_reason() noexcept;

private:
    std::vector<std::uint8_t> salt_;              // 32 bytes, per-install unique
    KyberKeypair kyber_;                           // public key; private in session
    WrappedKey wrapped_private_key_;             // encrypted private key on disk
    bool session_active_{false};

    // Session-only: plaintext private key in RAM. Erased on lock().
    mutable std::vector<std::uint8_t> session_private_key_;

    SMDU() = default;

    void scrub_(std::vector<std::uint8_t>& buf) const noexcept;
};

// ---------------------------------------------------------------------------
// Sentinel for when LFSSL is unavailable at compile time
// ---------------------------------------------------------------------------
struct SmdiSentinel {
    [[nodiscard]] static bool available() noexcept;
    [[nodiscard]] static std::string unavailable_reason() noexcept;
};

} // namespace hq::cerberus::privacy
